name: Terraform Apply - GKE Deployment

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # Change version if needed

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set GCP Project and Region
        run: |
          echo "GOOGLE_CLOUD_PROJECT=your-gcp-project-id" >> $GITHUB_ENV
          echo "GOOGLE_CLOUD_REGION=us-central1" >> $GITHUB_ENV  # Or change region if needed

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

