jobs:
  deploy:
    name: Terraform Apply on GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Create backend.tf file for GCS
        run: |
          cat > ./terraform/backend.tf <<EOF
          terraform {
            backend "gcs" {
              bucket = "your-gcs-bucket-name"
              prefix = "terraform/state"
            }
          }
          EOF

      - name: Terraform Init (with GCS backend)
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

