name: Terraform Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: ./terraform

    # Optional: Apply directly on main (use with caution)
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main'
    #   run: terraform apply -auto-approve -var-file="terraform.tfvars"
    #   working-directory: ./terraform
